dataset_name: 'vox1_test_wav_snr_5_Babble'
dataset_path: '../data/noisy_bg/vox1_test_wav_bq_noise/Babble/'

# max_len
#   set 0 if full length of audio is to be used, unforunately batching is broken for variable length audio and it is inefficient to use full length audio.
#   set to a value greater than 0 to use fixed length audio, audio will be repeated or cut to this length. pass in samples eq 16000 for 1 second audio.
#   4s = 64_000
max_len: 64_000
# batch_size

batch_size: 64
embeddings_output_path: '../embeds/noisy_bg/vox1_test_wav_bq_noise/Babble/'
results_output_path: '../results/noisy_bg/vox1_test_wav_bq_noise/Babble/'
dataset_type: 'voxceleb2'
audio_repeat: False
windowed: True
calculate_only_embeddings: False
# for config in ecapa campplus redimnet; do python src/main.py --model_config=$config; done
