dataset_path: '../data/voxceleb2_wav'
model_name: 'ecapa2'
max_len: 54_000 # 5 * 16000
batch_size: 32
fbank_processing: False
embeddings_output_path: '../embeds/'
results_output_path: '../results/'
device: 'mps'
