audio_repeat: false
batch_size: 64
calculate_only_embeddings: false
dataset_name: vox1_test_wav_snr_20_AirConditioner
dataset_path: ../data/metricgan/AirConditioner/
dataset_type: voxceleb2
embeddings_output_path: ../embeds/metricgan/AirConditioner/
max_len: 64000
results_output_path: ../results/metricgan/AirConditioner/
windowed: true
